### PR TITLE
Mod/11091 search page jump to sections

### PR DESCRIPTION
**Pull request by brianpetway**
**High level description:**

Improve the behavior of the jumpTo function on new search results page, especially when clicking on one of the links from the homepage Search Award Data section.

**Technical details:**

There was a typo in the code for these two buttons that link to the Categories section, preventing those from jumping to any section. I also changed the offset numbers in the jumpToSection function in SearchSectionWrapper, and I added a redux prop that becomes true afetr the map has loaded, and we don't call the jump function until then.
There is still some unavoidable variation in the exact spot where the jump function lands, due to the dependence on how quickly each section loads. You can see this by refreshing the page with the same hash and section in the url several times.

**JIRA Ticket:**
[DEV-11091](https://federal-spending-transparency.atlassian.net/browse/DEV-11091)

**Mockup:**
n/a

The following are ALL required for the PR to be merged:

Author:
- [x ] Linked to this PR in JIRA ticket
- [ ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [ ] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [ ] Verified mobile/tablet/desktop/monitor responsiveness
- [ ] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

### CODE REVIEW

**Review by anjenkin — CHANGES_REQUESTED** [review]
Is this happening for you? The page scrolls to the bottom and then jumps up but the wrong section is in view.   Maybe this is because my browser is pretty wide.  

https://github.com/fedspendingtransparency/usaspending-website/assets/121010/50630fbe-4997-43c8-ae4e-e00ba954ca21

**Comment by brianpetway** [comment]
I was seeing some variance in where the scroll landed each time, even when clicking the same button or refreshing the page with the hash in the url, but I don't recall seeing it go all the way to the bottom and back up like that.
I can do some more testing and look for that specifically.

**Comment by brianpetway** [comment]
I can't recreate that.
Is it happening that way for you every time?

**Comment by anjenkin** [comment]
> I can't recreate that. Is it happening that way for you every time?

yes, everytime

**Comment by brianpetway** [comment]
in safari or chrome?

**Comment by anjenkin** [comment]
> in safari or chrome?

Chrome

**Review by anjenkin — APPROVED** [review]

**Pull request merged**
