### PR TITLE
8729 add horiz scroll to search tables mod

### PR DESCRIPTION
**Pull request by brianpetway**
**High level description:**

Add a top scrollbar to the results table on Advanced Search page

**Technical details:**

Since this is a component that is used in five places, needed to make a prop for the topScroller and also needed to add it to the Keyword Search results table; the table (with three tabs) at the bottom of the Awards page should be unchanged, that table does not get the topScroller; I also removed a couple of functions from this component because they weren't actually ever being called and the code is confusing enough already

**JIRA Ticket:**
[DEV-8729](https://federal-spending-transparency.atlassian.net/browse/DEV-8729)

**Mockup:**
n/a

The following are ALL required for the PR to be merged:

Author:
- [x ] Linked to this PR in JIRA ticket
- [ ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [x ] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [x ] Verified mobile/tablet/desktop/monitor responsiveness
- [ ] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

### CODE REVIEW

**Comment by nick-torres** [comment]
It looks like the space between the bottom search bar and bottom of the table is smaller than the top of the table and top search bar
image
image

**Comment by nick-torres** [comment]
should we worry about this gray nub in the top right corner? 
image

**Comment by brianpetway** [comment]
Made changes to make those two things less visible, though they will still be visible if user zooms in, using browser or accessibility device

**Review by nick-torres — APPROVED** [review]
issues fixed

**Pull request merged**
