### PR TITLE
Update IDV Additional Information section

### PR DESCRIPTION
**Pull request by ebdabbs**
**High level description:**

Updates to the IDV summary page Additional Details section.

**Technical details:**
Subtasks:
- [DEV-2581](https://federal-spending-transparency.atlassian.net/browse/DEV-2581) updates to *Agency Details* labels
- [DEV-2582](https://federal-spending-transparency.atlassian.net/browse/DEV-2582) updates to *Parent Award Details* labels and removed `IDC Type`
- [DEV-2583](https://federal-spending-transparency.atlassian.net/browse/DEV-2583) for elements with both a code and a description, display `code`: `description` or `description` instead of just `code`
- [DEV-2584](https://federal-spending-transparency.atlassian.net/browse/DEV-2584) removed *Primary Place of Performance* section (for IDVs only)
- [DEV-2585](https://federal-spending-transparency.atlassian.net/browse/DEV-2585) updates to *Additional Details* section
- [DEV-2586](https://federal-spending-transparency.atlassian.net/browse/DEV-2586) updates to *Acquisition Details* label and removed `Category`
- [DEV-2587](https://federal-spending-transparency.atlassian.net/browse/DEV-2587) updates to *Competition Details* label and removed `Program`
- [DEV-2588](https://federal-spending-transparency.atlassian.net/browse/DEV-2588) updates to *Period of Performance* label and removed `Potential End Date` (for IDVs only)

Other:
- Also refactored to better organize files into `shared` and specific award type directories
- Renamed `AwardAmountsContainer` --> `IdvAmountsContainer` since that component is specific to IDVs
- Switched the Additional Info icons to use font awesome
- Use `--` instead of `not provided` when data is unavailable

**JIRA Ticket:**
[DEV-2492](https://federal-spending-transparency.atlassian.net/browse/DEV-2492)

**Mockup:**
https://bahdigital.invisionapp.com/share/NDIAADAZPUS#/screens/296001079_Award_Summary_2-0_-_IDV_-future-

The following are ALL required for the PR to be merged:
- [x] Code review
- [x] [API updates](https://github.com/fedspendingtransparency/usaspending-api/pull/1791) merged
- [x] Design review @AGuyNamedMarco 
- [x] Verified cross-browser compatibility

### CODE REVIEW

**Comment by AGuyNamedMarco** [comment]
Screen Shot 2019-05-06 at 11 11 41 AM

Thanks @ebdabbs – Looking very good!  Everything looks great, but I just noticed one field that has a code but not a description?

**Comment by ebdabbs** [comment]
@AGuyNamedMarco Do you have the url for the award with a missing description? It might be that the description isn't available in the data, in which case I've configured it to just show the code if it's available.

**Comment by jonhill13** [comment]
@ebdabbs 

1. [In #4 of the AC](https://federal-spending-transparency.atlassian.net/browse/DEV-2492) In `Parent Award Details`, if `Award Type` is NOT `IDC`, `IDC Type` value is `N/A`.  This PR has default values of `--` for properties with no data, which I am guessing is a design decision made after the fact.

2. [In #6 of the AC](https://federal-spending-transparency.atlassian.net/browse/DEV-2492) In `Competition Details`, display the value of the code, not the code itself. (maybe both?). On smaller screens the div cuts off the text. Do we want these divs to start scrolling at a certain length?

3. Just wanted to confirm you deleted those `png` files moved over to FontAwesome Icons.

4. [In #4 of the label updates](https://federal-spending-transparency.atlassian.net/browse/DEV-2582) "Single or Multiple Award IDV" >>> "Single or Multiple Parent Award IDV". This PR has `Multiple Or Single Parent Award IDV`

5. In competition details, `Evaluated Preference` says `NO PREFERENCE USED` should it be `--`?

6.  Moved a lot of files, just want to make sure they work with the other visuals those files are used in.

**Comment by ebdabbs** [comment]
@jonhill13 
1. See Ross's comment here: https://federal-spending-transparency.atlassian.net/browse/DEV-2582?focusedCommentId=39583&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-39583. I've updated the A/C in DEV-2492 to reflect that change.
2. @AGuyNamedMarco are you ok with allowing line breaks to prevent the text from getting cut off?
3. Yes, those pngs were replaced with FontAwesome.
4. Confirming with @AGuyNamedMarco - the screenshot has "Multiple Or Single ..."
5. `NO PREFERENCE USED` is coming from the data/API. `--` will only be displayed for falsy values.
6. Yep, we will have to watch out for merge conflicts but the changes should be compatible with other components of the IDV page.

**Comment by AGuyNamedMarco** [comment]
Looks great @ebdabbs – Thanks!

**Pull request merged**
