### PR TITLE
[DEV-7341] Recipient Box and whisker plot labels

### PR DESCRIPTION
**Pull request by afnazu**
**High level description:**

Add labels and formatted monetary values according to mock for top count, middle count, and bottom count

**Technical details:**
Implement labels using svg <text> and <tspan>
Implement money formatter to match values in mock

**JIRA Ticket:**
[DEV-7341](https://federal-spending-transparency.atlassian.net/browse/DEV-7341)

**Mockup:**
https://bahdigital.invisionapp.com/d/main#/console/14222398/296061875/preview
screenshot in [DEV-4344](https://federal-spending-transparency.atlassian.net/browse/DEV-4344)

The following are ALL required for the PR to be merged:

Author:
- [x] Linked to this PR in JIRA ticket
- [x] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [x] Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
- [x] Verified mobile/tablet/desktop/monitor responsiveness
- [x] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [x] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [n/a] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [n/a] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [x] Design review complete `if applicable`
- [n/a] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [x] Code review complete

### CODE REVIEW

**Comment by brett-varney** [comment]
@afnazu I'm sure this is an issue for designers, but at certain widths the labels overlap the donut area and page border:
image

**Review by brett-varney — APPROVED** [review]
This code is fine; there may be some updates before final.

**Comment by brett-varney** [comment]
@afnazu Sorry, I also just noticed: is the "middle" supposed to be right-aligned?

**Comment by afnazu** [comment]
@brett-varney Thanks! the middle text is supposed to be right aligned - will push updates for this and the overlapping labels

**Review by brett-varney — APPROVED** [review]
Still uncertain about text outside bounding box

**Review by brett-varney — APPROVED** [review]

**Pull request merged**
