### PR TITLE
Mod 9343 implement final mac for about the data release

### PR DESCRIPTION
**Pull request by chasls2**
**High level description:**

Updated About the Data from the Mac

**Technical details:**

Changed the wording for most of the md files from the mac
Added new md files with wording from the mac
Added new slugs and descriptions

**JIRA Ticket:**
[DEV-9343](https://federal-spending-transparency.atlassian.net/browse/DEV-9343)

**Mockup:**
https://invis.io/RYA3XN5WP#/273832670_Homepage_2-2_E

The following are ALL required for the PR to be merged:

Author:
- [x] Linked to this PR in JIRA ticket
- [ ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [x] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [x] Verified mobile/tablet/desktop/monitor responsiveness
- [x] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

### CODE REVIEW

**Comment by anjenkin** [comment]
Issues in File B text - 
Screen Shot 2022-12-09 at 11 55 37 AM

File C text missing period and last sentence - 

Screen Shot 2022-12-09 at 12 05 30 PM

File D2 - program should be singular

Screen Shot 2022-12-09 at 12 10 09 PM

Frequency of Updates to Agency Account Data  - There should be a link in the last sentence
Screen Shot 2022-12-09 at 12 45 25 PM

**Comment by anjenkin** [comment]
Financing Accounts - missing hyphen
Screen Shot 2022-12-09 at 12 53 46 PM

**Comment by chasls2** [comment]
Changes made. The only one I am unsure of is the hyphen in Financing Accounting. I took that as removing the hyphen? So add the hyphen back?

**Comment by anjenkin** [comment]
Under Sitewide Award Data Disclosures, "Start" is missing from the first entry in the list
Screen Shot 2022-12-09 at 3 19 28 PM

**Comment by anjenkin** [comment]
Under Sitewide Award Data Disclosures, "Start" is missing from the first entry in the list
Screen Shot 2022-12-09 at 3 19 28 PM

**Comment by anjenkin** [comment]
Typo in "Definition of Award Recipient (Entity Receiving a Federal Award)"

Screen Shot 2022-12-09 at 3 27 09 PM

**Comment by anjenkin** [comment]
Links missing from the entry below
Screen Shot 2022-12-09 at 3 30 46 PM

**Comment by anjenkin** [comment]
Missing links in entry
Screen Shot 2022-12-09 at 3 54 32 PM

**Comment by anjenkin** [comment]
Missing links in entry; also see circled typo
Screen Shot 2022-12-09 at 3 55 55 PM

**Comment by anjenkin** [comment]
Typo and comma missing from this entry
Screen Shot 2022-12-09 at 4 03 27 PM

**Comment by anjenkin** [comment]
Award Description Data Quality - Parentheses are missing around (Memorandum M-21-20) and (Memorandum M-22-12).
Screen Shot 2022-12-09 at 4 06 47 PM

**Comment by anjenkin** [comment]
Copy following the edits needs to be updated - 
Screen Shot 2022-12-09 at 4 14 11 PM

**Comment by anjenkin** [comment]
I think we're using the wrong slug here?  The entry copy is completely different (including the title)
Screen Shot 2022-12-09 at 4 18 10 PM

**Comment by anjenkin** [comment]
Missing t in Statutory 
Screen Shot 2022-12-09 at 4 19 31 PM

**Comment by anjenkin** [comment]
Unnecessary parentheses - 
Screen Shot 2022-12-09 at 4 24 00 PM

**Comment by anjenkin** [comment]
This entry was copy incorrectly.  It looks like the last line from the previous entry was used as the title here instead of the correct title.
Screen Shot 2022-12-09 at 4 28 13 PM

**Comment by anjenkin** [comment]
In AboutTheData.jsx need to add another instances of the AboutTheDataListView component for the new section added to the schema - 
Screen Shot 2022-12-09 at 4 33 34 PM

**Review by anjenkin — CHANGES_REQUESTED** [review]
see inline comments

**Comment by chasls2** [comment]
changes made

**Comment by anjenkin** [comment]
Typo in Limited Data for Unlinked Prime Awards (FEFC should be DEFC)

Screen Shot 2022-12-13 at 9 25 45 AM

**Comment by anjenkin** [comment]
Statement from the Department of Health and Human Services (HHS) – General and Targeted Distributions. 
.gov missing from usaspending at the end of the entry.
Screen Shot 2022-12-13 at 9 37 19 AM

**Comment by anjenkin** [comment]
The slug for "Statement from the Department of Health and Human Services (HHS) – Rural Health Clinic (RHC) Testing" is incorrect.  It should be "hhs-rhc".  Please correct the slug.  The "Statement from the Department of Health and Human Services (HHS) – Rural Health Clinic (RHC) Testing" and "Statement from the Department of the Treasury — Emergency Rental Assistance (ERA) and State and Local Fiscal Recovery Funds (SLFRF)" were using the same slug so please check and see if both entry have the correct text in the markdown files.  Both md files have incorrect text at the moment.  Let me know if you have any questions about this.

```
            {
                name: "Statement from the Department of Health and Human Services (HHS) – Rural Health Clinic (RHC) Testing",
                slug: "treasury-era-slfrf"
            },
```

**Comment by anjenkin** [comment]
For "Statement from the Department of the Treasury — Emergency Rental Assistance (ERA) and State and Local Fiscal Recovery Funds (SLFRF)". FFATA is missing from the circled area

Screen Shot 2022-12-13 at 11 59 02 AM

**Review by anjenkin — APPROVED** [review]

**Pull request merged**
