### PR TITLE
Fix/8671 homepage fit and finish

### PR DESCRIPTION
**Pull request by brianpetway**
**High level description:**

this ticket is the list of changes requested by design for the entire page

**Technical details:**

many small changes to css

**JIRA Ticket:**
[DEV-8671](https://federal-spending-transparency.atlassian.net/browse/DEV-8671)

**Mockup:**

https://app.zeplin.io/project/61f8076f4ef77f11fcc37f55/dashboard?sid=621fa593669231a368bf909c

The following are ALL required for the PR to be merged:

Author:
- [x ] Linked to this PR in JIRA ticket
- [ ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [x ] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [x ] Verified mobile/tablet/desktop/monitor responsiveness
- [x ] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

### CODE REVIEW

**Comment by nick-torres** [comment]
OCD review nitpicking 
based on https://app.zeplin.io/project/61f8076f4ef77f11fcc37f55/screen/621fa593669231a368bf909c
the hero buttons should have a shadow
the 'a targeted approach' section background gray color looks different in the mock vs the actual page

**Comment by nick-torres** [comment]
mobile mock comparison
https://app.zeplin.io/project/61f8076f4ef77f11fcc37f55/screen/621fa5ed0895a7acd657a247
Getting Started/on USAspending on different lines in the mock vs the branch
'whether you're a congressional staffer' section font looks slightly different in the mock vs the branch, might be a different font weight or color

**Comment by brianpetway** [comment]
Design asked us to remove the shadow from the hero buttons, but the mocks were not updated.

**Comment by brianpetway** [comment]
Background colors in those two sections have been adjusted

**Review by nick-torres — APPROVED** [review]
noticed a background color issue that was corrected and some other stuff that differed from the mock but was already noted in the AC

**Pull request merged**
