### PR TITLE
Dev-1937 Federal Accounts Tree View

### PR DESCRIPTION
**Pull request by jonhill13**
**High level description:**

Add Tree Map view to Federal Accounts

**Technical details:**

* Add Federal Account Tree Map component

* Add Federal Account Tree Tool Tip

**JIRA Ticket:**
[DEV-1937](https://federal-spending-transparency.atlassian.net/browse/DEV-1937)

**Mockup:**
https://bahdigital.invisionapp.com/share/69IA8EPGPCM#/screens/296001079

The following are ALL required for the PR to be merged:
- [x] Code review
- [x] Design review @AGuyNamedMarco 
- [x] Verified cross-browser compatibility

### CODE REVIEW

**Comment by AGuyNamedMarco** [comment]
Screen Shot 2019-05-06 at 11 27 18 AM

Thanks @jonhill13, looking solid. 

Notes on the design (see screenshot above):
- Fed. Account titles in treemap should be in bold.
- Funding Agency text in tooltip should be a link to its respective Agency Profile page.
- Tooltip does not hide when hovering outside of it.

Since there's a link within the tooltip, the user should be able to hover over the tooltip itself to click the link.

**Comment by jonhill13** [comment]
@AGuyNamedMarco Thanks for taking a look. 

- [x] Fed. Account titles in treemap should be in bold.

- [ ] Funding Agency text in tooltip should be a link to its respective Agency Profile page.
The current tooltips will not have the link due to time constraint and the link not being part of the AC. During creation, I noticed that I could not click on the links in the tooltips. We will have to create a new ticket for the links and actually staying on the tool tip during hover.

- [x] Tooltip does not hide when hovering outside of it.

**Comment by jonhill13** [comment]
@AGuyNamedMarco please check out the above comments.

**Comment by AGuyNamedMarco** [comment]
Screen Shot 2019-05-07 at 6 18 10 PM

Thanks @jonhill13 – It's looking really good.  I can approve the design, however I noticed an instance of a divergence in the colors of the treemap (comparison screenshot above):
http://localhost:3000/#/award/69452683

If we want to merge this, I'm okay with documenting it as a bug and then merging it.

**Pull request merged**
