### PR TITLE
DEV-9891 fix for redirects

### PR DESCRIPTION
**Pull request by nick-torres**
**High level description:**

you update the mapping in the buildredirectconfig file but then also have to run 3 jobs to actually execute the config (one per environment - qat, staging, prod)

**JIRA Ticket:**
[DEV-9891](https://federal-spending-transparency.atlassian.net/browse/DEV-9891)

The following are ALL required for the PR to be merged:

Author:
- [x] Linked to this PR in JIRA ticket
- [ ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [ ] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [ ] Verified mobile/tablet/desktop/monitor responsiveness
- [ ] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

### CODE REVIEW

**Comment by brianpetway** [comment]
You forgot about AC4, add 'the' to the title of this page

**Comment by brianpetway** [comment]
How can we test the redirect locally?

**Comment by nick-torres** [comment]
added 'the'

**Comment by nick-torres** [comment]
unless you run the redirect script, it can only be tested once it is in qat
there's a command to do it in the package.json but idk if it'll actually redirect locally

**Review by brianpetway — APPROVED** [review]

**Pull request merged**
