### PR TITLE
Dev-6614 Agency V2 Burn-up Chart Edge Case Obligation Exceeds Agency Budget

### PR DESCRIPTION
**Pull request by jonhill13**
**High level description:**

When obligations exceed the agency budget, the line and area shading will be red.

**Technical details:**

> • add gradients for the path and area path.
> • hide difference rectangle when obligations exceed the agency budget.

**JIRA Ticket:**
[DEV-6614](https://federal-spending-transparency.atlassian.net/browse/DEV-6614)

**Mockup:**
https://bahdigital.invisionapp.com/share/M8IAH1EZUH5#/screens/296060805

The following are ALL required for the PR to be merged:

Author:
- [x] Linked to this PR in JIRA ticket
- [x] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [x] Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
- [x] Verified mobile/tablet/desktop/monitor responsiveness
- [x] Verified that this PR does not create any *new* accessibility issues (37 vs 37 between local and qat) 
- [N/A] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [N/A] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [N/A] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [N/A] Design review complete `if applicable`
- [N/A] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [x] Code review complete

### CODE REVIEW

**Review by ebdabbs — COMMENTED** [review]
Looks great! I'm wondering if there is a good way to unit test that we correctly identify the obligation exceeds budget scenario

**Comment by jonhill13** [comment]
@ebdabbs I can certainly add tests. I had started, but that would involve accessing elements using the dom which is against react testing libraries best practices.

**Comment by ebdabbs** [comment]
@jonhill13 we could move[ this logic](https://github.com/fedspendingtransparency/usaspending-website/pull/2638/files#diff-f3c00c592832d42075ed3524da57e06e8326948f75dc0a899485d2036ecbf5c3R121) to a helper function and test that.. might be overkill

**Review by ebdabbs — APPROVED** [review]

**Comment by jonhill13** [comment]
@ebdabbs yeah, we should. It is all going to be re-written with this new PR or at least the scenario part since we need to treat the stopping point differently for each scenario.

```
const determineScenarios = (yScale, height, agencyBudget, data) => {
    const obligations = data.map((x) => x.obligated);
    const exceedsMax = Math.max(...obligations) > agencyBudget;
    const exceedsMin = Math.min(...obligations) < 0;
    if (exceedsMax && exceedsMin) return 'exceedsMaxAndMin';
    if (exceedsMax) return 'exceedsMax';
    if (exceedsMin) return 'exceedsMin';
    return 'normal';
};
```

**Pull request merged**
