### PR TITLE
Mod/9602 cd tooltip in place of performance

### PR DESCRIPTION
**Pull request by brianpetway**
**High level description:**

On Award profile pages, in the Additional Details section at the bottom of the page, in both the Place of Performance and Recipient Details accordions, change the address so that the Congressional District is last, then add the new CD tooltip to the end of that line; and add the Feature Flag to hise this in Prod

**Technical details:**

Both of these are made in the same loop in Accordion, so I added a state var to tell when to add this tooltip

**JIRA Ticket:**
[DEV-9602](https://federal-spending-transparency.atlassian.net/browse/DEV-9602)

**Mockup:**
n/a

The following are ALL required for the PR to be merged:

Author:
- [ x] Linked to this PR in JIRA ticket
- [ ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [ x] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [ x] Verified mobile/tablet/desktop/monitor responsiveness
- [ x] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

### CODE REVIEW

**Review by anjenkin — CHANGES_REQUESTED** [review]
Just wondering if the designers provided feedback because there are some differences from Zeplin but maybe the designers are ok with it?
* Per Zeplin, the icon hover color should be #555  
*  Icon sizing is different than Zeplin
*  Space from between the text and icon is wider than Zeplin

**Comment by brianpetway** [comment]
Design did sign off on the tooltip with ticket 9600.
There is no Zeplin link in these tickets. Which Zeplin link are you looking at?

**Comment by anjenkin** [comment]
@brianpetway Ok, that would be great if you could work with the design team to reconcile the differences here.  The mocks could be clearer here.

**Comment by brianpetway** [comment]
Thread with design about the info icons:
https://data-transparency-bfs.slack.com/archives/GGRP4UMAT/p1679583965130969

I changed the size of the new CD tooltip icons to be 14 to match the font-size

**Pull request merged**
