### PR TITLE
Mod/10878 table row height and links

### PR DESCRIPTION
**Pull request by brianpetway**
**High level description:**

Add prop to set row height in dtui Table; in table cells with links make the entire cell clickable

**Technical details:**

Ended up adding a rowHeight prop for the table body and headerRowHeight prop for the header; changed the way the td cells height is calculated and changed the css width to 100% so the a tag is the full height and width of parent td

IMPORTANT DEV NOTE: in order to see the row heights applied correctly, you need to set the columnWidths to more than 144px, either in the columns data object sent to the dtui Table, or you can force it in the dtui TableHeader.jsx, line 103, where the columnWidth is applied to the th element

**JIRA Ticket:**
[DEV-10878](https://federal-spending-transparency.atlassian.net/browse/DEV-10878)

**Mockup:**
https://app.zeplin.io/project/61f8076f4ef77f11fcc37f55/screen/660389a02a5e608bca8bef65

The following are ALL required for the PR to be merged:

Author:
- [ x] Linked to this PR in JIRA ticket
- [ ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [ ] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [ ] Verified mobile/tablet/desktop/monitor responsiveness
- [ ] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

### CODE REVIEW

**Comment by anjenkin** [comment]
@brianpetway Is the column width set in this branch because I'm not seeing the two line row height set without changing any code in this branch.  Also there is a merge conflict

Screenshot 2024-05-22 at 9 46 51 PM

**Comment by brianpetway** [comment]
I merged qat in to get rid of the conflicts.

No, there aren't any changes to any column widths in this branch. 
There is a note in the pr explaining that you need to set the column widths in order to see the rowHeight work.

**Comment by anjenkin** [comment]
@brianpetway This is what I'm seeing when the column width is set to 145px in the columns data object sent to the dtui Table


Screenshot 2024-05-23 at 11 45 49 AM

**Comment by brianpetway** [comment]
It looks like the cells have some issues with the text expanding outside at that size.
But the samllest column width we're going to use is 200.

**Comment by anjenkin** [comment]
I'm seeing this with the latest from the DTUI branch.  Am I missing something?

Screenshot 2024-05-23 at 8 09 58 PM

**Review by anjenkin — CHANGES_REQUESTED** [review]
This looks good.  Couple things, per the note in the ticket this needs to go through design review before we merge it in.

Also, the designers will probably noticed that the cell margins are not equal on the top and bottom of the cells that have two lines of text. See screenshot below.  The margins on the <a> tag look correct (ie. 8px top and bottom) but there's extra space above the <a> tag that shouldn't be there.

Screenshot 2024-05-24 at 5 56 13 PM

https://app.zeplin.io/project/61f8076f4ef77f11fcc37f55/screen/660389a384f9982136467d23

**Comment by anjenkin** [comment]
@brianpetway There's a package-lock conflict. Also I noticed after I merged in the DTUI change that the right border is missing from the table - 

Screenshot 2024-05-29 at 1 48 48 PM

**Review by anjenkin — APPROVED** [review]

**Pull request merged**
