### PR TITLE
Mod 9522 add recipient video to training videos page

### PR DESCRIPTION
**Pull request by chasls2**
**High level description:**

**Technical details:**

Technical details for the knowledge of other developers.

**JIRA Ticket:**
[DEV-9522](https://federal-spending-transparency.atlassian.net/browse/DEV-9522)

**Mockup:**
https://invis.io/RYA3XN5WP#/273832670_Homepage_2-2_E

The following are ALL required for the PR to be merged:

Author:
- [x] Linked to this PR in JIRA ticket
- [ ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [x] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [x] Verified mobile/tablet/desktop/monitor responsiveness
- [x] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

### CODE REVIEW

**Comment by chasls2** [comment]
Some how an uneeded link was added.. I am not sure how but it did

**Comment by anjenkin** [comment]
@chasls2 That would be great if you could change this branch to merge to QAT.  You should consider adding a reminder in your notes to always merge to QAT so this doesn't continue to happen. Thank you!

**Comment by chasls2** [comment]
[src/js/dataMapping/trainingVideos/playListMetadata.js](https://github.com/fedspendingtransparency/usaspending-website/pull/3478/files#diff-0682668d90e3b532b992ff84bc6595a9566cbd3a55e735e052fe7ba8cd9cf734)

there was an unneeded link that was added, highlighted below

image

**Comment by anjenkin** [comment]
There's a space missing in the description - 
Screenshot 2023-02-14 at 11 11 31 AM

**Comment by chasls2** [comment]
its in there?

I just double checked. 

and it loaded properly for me..

**Comment by chasls2** [comment]
annnnd no it wasn't. Sorry.

**Review by anjenkin — CHANGES_REQUESTED** [review]
Now the link near the end of the description is incorrect.    
Screenshot 2023-02-14 at 12 56 46 PM

**Review by anjenkin — APPROVED** [review]

**Pull request merged**
