### PR TITLE
DEV-9542 update explainer

### PR DESCRIPTION
**Pull request by nick-torres**
**High level description:**

update explainer text on advanced search page

**Technical details:**

simple styling, a lot of hoops to jump through for ReadMore component bc of the glossary links in the text

**JIRA Ticket:**
[DEV-9542](https://federal-spending-transparency.atlassian.net/browse/DEV-9542)

**Mockup:**
https://app.zeplin.io/project/61f8076f4ef77f11fcc37f55/screen/63f53dc72f58782e5fdf7702

The following are ALL required for the PR to be merged:

Author:
- [x] Linked to this PR in JIRA ticket
- [x] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [x] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [x] Verified mobile/tablet/desktop/monitor responsiveness
- [ ] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

### CODE REVIEW

**Comment by nick-torres** [comment]
this is good to go - only one remaining issue which is the font-size on the table tab should be 14 not 16 px. i've made the change locally but just can't push it until my vpn token issues are resolved and idk when that will be

**Comment by brianpetway** [comment]
Conflicts in package-lock.

It seems like you spoke to the designers and changed the design for the read more for the tabs other than Table, the tabs that have the blue box to the right of the text. I say this because they are consistently different than the mock, all in the same way, with only one line of text before the ellipsis and 'read more'.
If this is the case you should note it in the ticket so QA can know.

In the Categories tab, Prime Awards, the first sentence of the text from the Table tab is present and should be removed.

The Time tab and Categories tab, Sub-Awards, both need a space after the Prime Awards Glossary icon.

**Comment by nick-torres** [comment]
@brianpetway idk what you're talking about with that second paragraph

**Comment by brianpetway** [comment]
In all the tabs other than Table, you're showing one line of text.
The mock, and the Table tab, show two lines of text.

**Comment by nick-torres** [comment]
ah the text is completely different from what the designers used for the mocks, jessica was fine with how it looked but okay yeah i will mention it to allie - also for the comment about the categories tab, the ticket says to add the text under the existing text for the tab which so happens to match what the table tab says, it's a coincidence not a mistake "Add text below current Categories text as new paragraph below existing text"

i'll fix package lock, and spaces for the two tabs when i can reliably pull/push code

**Review by anjenkin — DISMISSED** [review]
Changing the line clamp on the geo tab doesn't increase the number of lines of text displayed.
Screenshot 2023-03-07 at 11 32 11 AM

The text on the time tab isn't bottom aligned with the tabs after increasing the line clamp to 2.
Screenshot 2023-03-07 at 11 32 21 AM

I'm ok with fixing these as a separate ticket next sprint.

**Comment by nick-torres** [comment]
> Changing the line clamp on the geo tab doesn't increase the number of lines of text displayed. Screenshot 2023-03-07 at 11 32 11 AM
> 
> The text on the time tab isn't bottom aligned with the tabs after increasing the line clamp to 2. Screenshot 2023-03-07 at 11 32 21 AM
> 
> I'm ok with fixing these as a separate ticket next sprint.

the first issue - jessica was aware of, with how i had to do the preview functionality theres only one line of text on the geo tab, thus it can't line clamp 2 lines when there is only one line to clamp

this is bc of the download data by year component on the page, in order to make it truly bottom aligned that would have to be moved to its own row

**Review by brianpetway — APPROVED** [review]

**Review by brianpetway — APPROVED** [review]

**Pull request merged**
