### PR TITLE
Ftr/9374 featured video

### PR DESCRIPTION
**Pull request by chasls2**
**High level description:**
,create the feature video section

**Technical details:**

Technical details for the knowledge of other developers.

**JIRA Ticket:**
[DEV-9374][(https://federal-spending-transparency.atlassian.net/browse/DEV-1234](https://federal-spending-transparency.atlassian.net/browse/DEV-9374))

**Mockup:**
https://invis.io/RYA3XN5WP#/273832670_Homepage_2-2_E

The following are ALL required for the PR to be merged:

Author:
- [x] Linked to this PR in JIRA ticket
- [x] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [x] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [x] Verified mobile/tablet/desktop/monitor responsiveness
- [x] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

### CODE REVIEW

**Comment by nick-torres** [comment]
needs to be to qat

**Comment by anjenkin** [comment]
@chasls2 is this ready for review?  The PR is still in draft.  Just checking...

**Comment by chasls2** [comment]
trying to get the play button and duration to show correctly

**Comment by nick-torres** [comment]
is the text supposed to underline when you mouse over it??

**Comment by chasls2** [comment]
Yes, as per the original design review request.

What I am having an issue with now if anyone is free, is everything is where it needs to be on the page, but the pig img is slight off the bottom due to the duration component

https://data-transparency-bfs.slack.com/archives/GGRP4UMAT/p1672762201539749

**Comment by chasls2** [comment]
wait.. now its not doing it.. and I didn't change anything

**Review by nick-torres — APPROVED** [review]

**Pull request merged**
